name = "JuliaStuff"
uuid = "e0737972-1b09-4fbf-ae2a-fd061b97b7dd"
authors = ["John Waczak"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
